Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/envs/rapids/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import time

from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster

cluster = LocalCUDACluster()
client = Client(cluster)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_536/3457759813.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0;32mfrom[0m [0mdask[0m[0;34m.[0m[0mdistributed[0m [0;32mimport[0m [0mClient[0m[0;34m,[0m [0mwait[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mfrom[0m [0mdask_cuda[0m [0;32mimport[0m [0mLocalCUDACluster[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0mcluster[0m [0;34m=[0m [0mLocalCUDACluster[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m<frozen zipimport>[0m in [0;36mload_module[0;34m(self, fullname)[0m

[0;32m/opt/conda/envs/rapids/lib/python3.9/site-packages/dask_cuda-22.12.0a0+gb3ed902-py3.9.egg/dask_cuda/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0;32mfrom[0m [0;34m.[0m[0m_version[0m [0;32mimport[0m [0mget_versions[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 12[0;31m [0;32mfrom[0m [0;34m.[0m[0mcuda_worker[0m [0;32mimport[0m [0mCUDAWorker[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     13[0m [0;32mfrom[0m [0;34m.[0m[0mexplicit_comms[0m[0;34m.[0m[0mdataframe[0m[0;34m.[0m[0mshuffle[0m [0;32mimport[0m [0mget_rearrange_by_column_tasks_wrapper[0m[0;34m[0m[0;34m[0m[0m
[1;32m     14[0m [0;32mfrom[0m [0;34m.[0m[0mlocal_cuda_cluster[0m [0;32mimport[0m [0mLocalCUDACluster[0m[0;34m[0m[0;34m[0m[0m

[0;32m<frozen zipimport>[0m in [0;36mload_module[0;34m(self, fullname)[0m

[0;32m/opt/conda/envs/rapids/lib/python3.9/site-packages/dask_cuda-22.12.0a0+gb3ed902-py3.9.egg/dask_cuda/cuda_worker.py[0m in [0;36m<module>[0;34m[0m
[1;32m     19[0m [0;34m[0m[0m
[1;32m     20[0m [0;32mfrom[0m [0;34m.[0m[0mdevice_host_file[0m [0;32mimport[0m [0mDeviceHostFile[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 21[0;31m [0;32mfrom[0m [0;34m.[0m[0minitialize[0m [0;32mimport[0m [0minitialize[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     22[0m [0;32mfrom[0m [0;34m.[0m[0mproxify_host_file[0m [0;32mimport[0m [0mProxifyHostFile[0m[0;34m[0m[0;34m[0m[0m
[1;32m     23[0m from .utils import (

[0;32m<frozen zipimport>[0m in [0;36mload_module[0;34m(self, fullname)[0m

[0;32m/opt/conda/envs/rapids/lib/python3.9/site-packages/dask_cuda-22.12.0a0+gb3ed902-py3.9.egg/dask_cuda/initialize.py[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0;32mimport[0m [0mdask[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;32mimport[0m [0mdistributed[0m[0;34m.[0m[0mcomm[0m[0;34m.[0m[0mucx[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m [0;32mfrom[0m [0mdistributed[0m[0;34m.[0m[0mdiagnostics[0m[0;34m.[0m[0mnvml[0m [0;32mimport[0m [0mget_device_index_and_uuid[0m[0;34m,[0m [0mhas_cuda_context[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0;32mfrom[0m [0;34m.[0m[0mutils[0m [0;32mimport[0m [0mget_ucx_config[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: cannot import name 'get_device_index_and_uuid' from 'distributed.diagnostics.nvml' (/opt/conda/envs/rapids/lib/python3.9/site-packages/distributed/diagnostics/nvml.py)
ImportError: cannot import name 'get_device_index_and_uuid' from 'distributed.diagnostics.nvml' (/opt/conda/envs/rapids/lib/python3.9/site-packages/distributed/diagnostics/nvml.py)

